In [4]:
import pandas as pd
import numpy as np
df=pd.read_csv("C:\\Users\\HP\\Desktop\\Diabetes-Prediction-System\\data\\diabetes_clean.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,169.5,33.6,0.627,50.0,1
1,1.0,85.0,66.0,29.0,102.5,26.6,0.351,31.0,0
2,8.0,183.0,64.0,32.0,169.5,23.3,0.672,32.0,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0.0,137.0,40.0,35.0,168.0,43.1,1.200,33.0,1

In [6]:
def bmi_category(bmi):
    if bmi < 18.5:
        return "Underweight"
    elif bmi < 25:
        return "Normal"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

df["BMI_Category"] = df["BMI"].apply(bmi_category)

df[["BMI", "BMI_Category"]].head()

    BMI BMI_Category
0  33.6        Obese
1  26.6   Overweight
2  23.3       Normal
3  28.1   Overweight
4  43.1        Obese

In [8]:
def age_group(age):
    if age < 30:
        return "Young"
    elif age < 50:
        return "Middle"
    else:
        return "Old"

df["Age_Group"] = df["Age"].apply(age_group)

df[["Age", "Age_Group"]].head()

    Age Age_Group
0  50.0       Old
1  31.0    Middle
2  32.0    Middle
3  21.0     Young
4  33.0    Middle

In [10]:
def glucose_category(glucose):
    if glucose < 100:
        return "Normal"
    elif glucose < 140:
        return "Prediabetes"
    else:
        return "Diabetes"

df["Glucose_Level"] = df["Glucose"].apply(glucose_category)

df[["Glucose", "Glucose_Level"]].head()

   Glucose Glucose_Level
0    148.0      Diabetes
1     85.0        Normal
2    183.0      Diabetes
3     89.0        Normal
4    137.0   Prediabetes

In [12]:
df["BMI_Age_Interaction"] = df["BMI"] * df["Age"]

df[["BMI", "Age", "BMI_Age_Interaction"]].head()

    BMI   Age  BMI_Age_Interaction
0  33.6  50.0               1680.0
1  26.6  31.0                824.6
2  23.3  32.0                745.6
3  28.1  21.0                590.1
4  43.1  33.0               1422.3

In [16]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,BMI_Category,Age_Group,Glucose_Level,BMI_Age_Interaction
0,6.0,148.0,72.0,35.0,169.5,33.6,0.627,50.0,1,Obese,Old,Diabetes,1680.0
1,1.0,85.0,66.0,29.0,102.5,26.6,0.351,31.0,0,Overweight,Middle,Normal,824.6
2,8.0,183.0,64.0,32.0,169.5,23.3,0.672,32.0,1,Normal,Middle,Diabetes,745.6
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0,Overweight,Young,Normal,590.1
4,0.0,137.0,40.0,35.0,168.0,43.1,1.200,33.0,1,Obese,Middle,Prediabetes,1422.3

In [17]:
df.to_csv("C:\\Users\\HP\\Desktop\\Diabetes-Prediction-System\\data\\diabetes_featured.csv")

##  Feature Engineering Summary

- Created BMI categories based on health standards
- Grouped age into meaningful life stages
- Categorized glucose levels based on medical thresholds
- Added interaction feature (BMI × Age)

These transformations improve interpretability and model learning.